apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-convtemp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: convtemp
  template:
    metadata:
      labels:
        app: convtemp
    spec:
      containers:
      - name: temperatura
        image: fernandord/conversao-temperatura:latest
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
          - containerPort: 8080
            name: porta

